### ISSUE TITLE
DRM Not work on Libreelec 20 Beta2

### ISSUE THREAD

**Issue by Mannshoch** [rbuehlma/pvr.zattoo#167]
System: Libreelec 20 Beta 2

If I open several TV station. A DRM error appear on screen.
https://paste.kodi.tv/adilosixik.kodi

**Comment by rbuehlma** [comment]
This is discussed here:

https://www.kodinerds.net/index.php/Thread/58635-PVR-Addon-f%C3%BCr-Zattoo-und-Reseller/?postID=711397#post711397

Zattoo has changed their DRM configuration for all RTL channels such that it requires a security level which is not supported by Linux anymore.

I'm not aware of any possibilities to fix this.

**Comment by Mannshoch** [comment]
Thanks for the Information. I rised a ticket on zattoo about that. 

Currently, their FAQ about this problem says, that it was usefull for 0 of 18 viewers - I assume that they all are Linux users

Could you, propose a good replacement for a IP-TV for kodi if you life in Switzerland?

**Comment by rbuehlma** [comment]
This has been fixed. The channels can be streamed again but with reduced quality due to DRM restriction.

**Comment by Mannshoch** [comment]
How long does it need until we resceive it in Kodi?

**Comment by Mannshoch** [comment]
@rbuehlma  It works nice. Searching for a replay and play It does work fine. But If you record it and play it from the recordings does not. A DRM message still appear.

**Comment by Mannshoch** [comment]
Since today the same situation again. Several tv channel not work.
